export const GET_POST = 'GET_POST';
export const GET_POST_PENDING = 'GET_POST_PENDING';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';
